[package]
name = "gensym"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
#once_cell = "1.17.0"
unicode-normalization-alignments = "0.1.12"